GET http://localhost:3000/movies/
###

DELETE http://localhost:3000/movies/2/
###

GET http://localhost:3000/directors/:directorId/movies/
###

GET http://localhost:3000/movies/12/
###

GET http://localhost:3000/directors/
###

GET http://localhost:3000/directors/4/movies/
###

GET http://localhost:3000/
###

